<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="3" hostname="LAPTOP-DI1V5LOI" failures="1" tests="2" name="Default test(failed)" time="0.046" errors="0" timestamp="2023-02-14T09:33:47 CST">
  <testcase classname="demo.TestNGRetryfaileddemo" name="Test3" time="0.01">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at demo.TestNGRetryfaileddemo.Test3(TestNGRetryfaileddemo.java:22)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- Test3 -->
  <testcase classname="demo.TestNGRetryfaileddemo" name="Test2" time="0.001"/>
  <testcase classname="demo.TestNGRetryfaileddemo" name="Test5" time="0.0">
    <ignored/>
  </testcase> <!-- Test5 -->
  <testcase classname="demo.TestNGRetryfaileddemo" name="Test4" time="0.0">
    <ignored/>
  </testcase> <!-- Test4 -->
  <testcase classname="demo.TestNGRetryfaileddemo" name="Test1" time="0.0">
    <ignored/>
  </testcase> <!-- Test1 -->
</testsuite> <!-- Default test(failed) -->
